apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: IfNotPresent # Safe policy for public images
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data-storage
              mountPath: /data/db
      volumes:
        - name: mongo-data-storage
          persistentVolumeClaim:
            claimName: mongo-pvc # Maps securely to managed storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Allocates 5GB of virtual storage for your data
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP